#server port
#server.port=8081
##database configuration for mysql:-
#spring.datasource.url=jdbc:mysql://localhost:3306/dev_env
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
###hibernate configuration for mysql:-
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true  
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#database configuration for postgresql:-
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=shann
#spring.datasource.password=Admin

#hibernate configuration for postgresql:-
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true  


#loggers
#logging.level.s7.Application= WARN
#logging.level.org.springframework.web= ERROR
#logging.level.com.school.services= TRACE

#logging pattern for the console
#logging.pattern.console= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

#Spring Security
#spring.security.user.name=zss
#spring.security.user.password=ass

#logging pattern for file
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

logging.file=C:/Users/ZEESHAN/Desktop/zapi.log

#Swagger Config
#swagger.server.url=http://localhost:8080/schoolapi
# swagger-ui custom path
#springdoc.swagger-ui.path=http://localhost:8080/schoolapi
